# Generated by Django 5.0.2 on 2024-03-18 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_alter_programming_body_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='programming',
            name='likes',
            field=models.ManyToManyField(related_name='prblog', to=settings.AUTH_USER_MODEL),
        ),
    ]
