# Generated by Django 5.0.2 on 2024-03-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlapp', '0003_htmlpost_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlpost',
            options={'ordering': ['date_added']},
        ),
    ]
