# Generated by Django 5.0.2 on 2024-03-18 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adv_css', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adv_css',
            name='likes',
            field=models.ManyToManyField(related_name='cssblog', to=settings.AUTH_USER_MODEL),
        ),
    ]
