# Generated by Django 5.0.2 on 2024-03-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adv_css', '0002_adv_css_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adv_css',
            options={'ordering': ['date_added']},
        ),
    ]
