# Generated by Django 5.0.2 on 2024-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini_sheet',
            name='action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Revisit', 'Revisit')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='mini_sheet',
            name='gfg_link',
            field=models.URLField(blank=True, null=True, verbose_name='GeeksforGeeks Link'),
        ),
        migrations.AddField(
            model_name='mini_sheet',
            name='leetcode_link',
            field=models.URLField(blank=True, null=True, verbose_name='LeetCode Link'),
        ),
        migrations.AddField(
            model_name='mini_sheet',
            name='notes_pdf_link',
            field=models.URLField(blank=True, null=True, verbose_name='Notes PDF Link'),
        ),
        migrations.AddField(
            model_name='mini_sheet',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
        migrations.AlterField(
            model_name='mini_sheet',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
