# Generated by Django 5.0.2 on 2024-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepration_sheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepration_sheet',
            name='gfg_link',
            field=models.URLField(blank=True, null=True, verbose_name='GeeksforGeeks Link'),
        ),
        migrations.AddField(
            model_name='prepration_sheet',
            name='leetcode_link',
            field=models.URLField(blank=True, null=True, verbose_name='LeetCode Link'),
        ),
        migrations.AddField(
            model_name='prepration_sheet',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Link'),
        ),
        migrations.AlterField(
            model_name='prepration_sheet',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
