# Generated by Django 5.0.2 on 2024-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prepration_sheet', '0002_prepration_sheet_gfg_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepration_sheet',
            name='action',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Revisit', 'Revisit')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prepration_sheet',
            name='notes_pdf_link',
            field=models.URLField(blank=True, null=True, verbose_name='Notes PDF Link'),
        ),
    ]
