# Generated by Django 5.0.2 on 2024-03-14 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_sheet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cp_sheet',
            name='likes',
            field=models.ManyToManyField(related_name='cp_sheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
