# Generated by Django 5.0.2 on 2024-03-18 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_sheet', '0002_cp_sheet_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cp_sheet',
            name='likes',
            field=models.ManyToManyField(related_name='cpsheet', to=settings.AUTH_USER_MODEL),
        ),
    ]
