# Generated by Django 5.0.2 on 2024-03-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
            ],
            options={
                'indexes': [models.Index(fields=['remark'], name='remark_idx')],
            },
        ),
    ]
