# Generated by Django 5.0.2 on 2024-03-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_yourmodel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='yourmodel',
            name='remark_idx',
        ),
    ]
