# Generated by Django 5.0.2 on 2024-03-27 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_yourmodel_remark_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
