# Generated by Django 5.0.2 on 2024-03-28 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
